version: 2
models:
  - name: covalent__
    columns:
      - name: get
        tests:
          - test_udf:
              name: test_covalent__get_status_200
              args: >
                '/v1/1/block_v2/5000000/'
                , {}
              assertions:
                - result:status_code = 200
