version: 2
models:
  - name: groq__
    columns:
      - name: chat_completions
        tests:
          - test_udf_without_context:
              name: test_groq__chat_completions_simple
              args: >
                [{'role': 'user', 'content': 'Hello, how are you?'}],
                'llama3-8b-8192'
              assertions:
                - result:data:choices IS NOT NULL
                - result:data:model IS NOT NULL

      - name: quick_chat
        tests:
          - test_udf_without_context:
              name: test_groq__quick_chat_single_message
              args: >
                'Hello, how are you?',
                'llama3-8b-8192'
              assertions:
                - result:data:choices IS NOT NULL


      - name: extract_response_text
        tests:
          - test_udf_without_context:
              name: test_groq__extract_response_text
              args: >
                {'choices': [{'message': {'content': 'Hello there!'}}]}
              assertions:
                - result = 'Hello there!'
          - test_udf_without_context:
              name: test_groq__extract_response_text_error
              args: >
                {'error': {'message': 'API Error occurred'}}
              assertions:
                - result = 'API Error occurred'

