version: 2
models:
  - name: claude__
    columns:
      - name: post_messages
        tests:
          - test_udf:
              name: test_claude__post_messages_only_one_message
              args: >
                [{'role': 'user', 'content': 'Hello, how are you?'}]
              assertions:
                - result:status_code = 200
                - result:error IS NULL
          - test_udf:
              name: test_claude__post_messages_with_model
              args: >
                'claude-3-5-sonnet-20241022',
                [{'role': 'user', 'content': 'Hello, how are you?'}],
                1024
              assertions:
                - result:status_code = 200
          - test_udf:
              name: test_claude__post_messages_with_all_params
              args: >
                'claude-3-5-sonnet-20241022',
                [{'role': 'user', 'content': 'Hello, how are you?'}],
                1024,
                0.5,
                10,
                0.95,
                'You are a helpful assistant.'
              assertions:
                - result:status_code = 200
                - result:error IS NULL

      - name: count_message_tokens
        tests:
          - test_udf:
              name: test_claude__count_message_tokens
              args: >
                'claude-3-5-sonnet-20241022',
                [{'role': 'user', 'content': 'Hello, how are you?'}]
              assertions:
                - result:status_code = 200
                - result:error IS NULL

      - name: list_models
        tests:
          - test_udf:
              name: test_claude__list_models
              assertions:
                - result:status_code = 200
                - result:error IS NULL

      - name: get_model
        tests:
          - test_udf:
              name: test_claude__get_model
              args: >
                'claude-3-5-sonnet-20241022'
              assertions:
                - result:status_code = 200
                - result:error IS NULL

      - name: post_messages_batch
        tests:
          - test_udf:
              name: test_claude__post_messages_batch
              args: >
                {
                  'requests': [
                    {
                      'custom_id': 'test_1',
                      'params': {
                        'model': 'claude-3-5-sonnet-20241022',
                        'max_tokens': 100,
                        'messages': [{'role': 'user', 'content': 'Say hello'}]
                      }
                    },
                    {
                      'custom_id': 'test_2',
                      'params': {
                        'model': 'claude-3-5-sonnet-20241022',
                        'max_tokens': 100,
                        'messages': [{'role': 'user', 'content': 'Say goodbye'}]
                      }
                    }
                  ]
                }
              assertions:
                - result:status_code = 200
                - result:error IS NULL
                - result:data:id IS NOT NULL
                - result:data:type = 'message_batch'

      - name: list_message_batches
        tests:
          - test_udf:
              name: test_claude__list_message_batches
              assertions:
                - result:status_code = 200
                - result:error IS NULL
                - result:data IS NOT NULL

      # Skip pagination tests that require valid batch IDs
      - name: list_message_batches_with_before
        tests:
          - test_udf:
              config:
                enabled: false
              name: test_claude__list_message_batches_with_before_disabled
              args: >
                null,
                5
              assertions:
                - result:status_code = 200

      - name: list_message_batches_with_after
        tests:
          - test_udf:
              config:
                enabled: false
              name: test_claude__list_message_batches_with_after_disabled
              args: >
                null,
                5
              assertions:
                - result:status_code = 200

      # Skip individual batch access tests that require valid batch IDs
      - name: get_message_batch
        tests:
          - test_udf:
              config:
                enabled: false
              name: test_claude__get_message_batch_disabled
              args: >
                'msgbatch_test'
              assertions:
                - result:status_code = 404

      - name: get_message_batch_results
        tests:
          - test_udf:
              config:
                enabled: false
              name: test_claude__get_message_batch_results_disabled
              args: >
                'msgbatch_test'
              assertions:
                - result:status_code = 404
