version: 2
models:
  - name: claude__
    columns:
      - name: post
        tests:
          - test_udf:
              name: test_claude__post_status_200
              args: >
                '/v1/messages'
                , {'messages': [{'role': 'user', 'content': 'Hello, how are you?'}]}
              assertions:
                - result:status_code = 200
                - result:error IS NULL
