version: 2
models:
  - name: fred__
    columns:
      - name: get_series
        tests:
          - test_marketplace_udf:
              name: test_fred__get_series_status_200
              args: >
                {
                  'series_id': 'CORESTICKM679SFRBATL',
                  'file_type': 'json'
                }

              validations:
                - result:status_code = 200