version: 2
models:
  - name: coingecko__
    columns:
      - name: get
        tests:
          - test_udf:
              name: test_coingecko__get_status_200
              args: >
                '/api/v3/simple/price'
                , {'ids': '0x', 'vs_currencies': 'btc,usd,eth'}
              assertions:
                - result:status_code = 200
