version: 2
models:
  - name: topshot__
    columns:
      - name: graphql
        tests:
          - test_udf:
              name: test_topshot__graphql_status_200
              args: >
                {
                  'query': '
                    query {
                      getMintedMoment (momentId: 5) {
                          data {
                              id
                          }
                      }
                  }
                }',
                  'variables': '{}'
                }
              assertions:
                - result:status_code = 200
