version: 2
models:
  - name: cmc__
    columns:
      - name: get
        tests:
          - test_udf:
              name: test_cmc__get_status_200
              args: >
                '/v2/cryptocurrency/ohlcv/historical'
                , {'interval': 'hourly', 'time_period': 'hourly', 'time_start': 1691524740, 'time_end': 1691528400, 'id': '15478,15479'}
              assertions:
                - result:status_code = 200
