version: 2
models:
  - name: secrets
    columns:
      - name: udf_register_secret
        tests:
          - test_udf:
              name: test_secrets__udf_register_secret
              args: >
                'test', 'test'
              assertions:
              - result = {'request_id':'test','success':false}
      - name: udf_get_secret
        tests:
          - test_udf:
              name: test_secrets__udf_get_secret
              args: >
                'test'
              assertions:
                - >
                  result::OBJECT = {'key': 'value'}
      - name: udf_get_secrets
        tests:
          - test_udf:
              name: test_secrets__udf_get_secrets
              args: ''
              assertions:
                - >
                  result = {'test': {'key': 'value'}}
      - name: udf_create_secret
        tests:
          - test_udf:
              name: test_secrets__udf_create_secret
              args: >
                'test', {'key': 'value'}
              assertions:
                - result = 200
      - name: udf_delete_secret
        tests:
          - test_udf:
              name: test_secrets__udf_delete_secret
              args: >
                'test_delete'
              assertions:
                - result = 200