version: 2
models:
  - name: blockpour_utils__
    columns:
      - name: udf_json_rpc_call
        tests:
          - test_udf:
              args: "'foo', [], 1"
              expected: >
                {
                'jsonrpc': '2.0',
                'method': 'foo',
                'params': [],
                'id': '1'
                }

