version: 2
models:
  - name: blockpour_utils__
    columns:
      - name: get
        tests:
          - test_udf:
              name: test_blockpour_utils__get_status_200
              args: >
                '/v1/tokens/1/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', {
                  'blockNumber': 17767007
                }
              assertions:
                - result:status_code = 200

      - name: post
        tests:
          - test_udf:
              name: test_blockpour_utils__post_status_200
              args: >
                '/v1/model/run', {
                  'slug': 'price.quote',
                  'version': '1.0',
                  'chainId': 1,
                  'blockNumber': 17767016,
                  'input': {}
                }
              assertions:
                - result:status_code = 200
