name: dbt_run_adhoc
run-name: ${{ inputs.environment }} - ${{ inputs.dbt_command }}

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: DBT Run Environment
        required: true
        options:
          - dev
          - prod
          - hosted
        default: dev
      warehouse:
        type: choice
        description: Snowflake warehouse
        required: true
        options:
          - DBT
          - DBT_CLOUD
          - DBT_EMERGENCY
        default: DBT
      dbt_command:
        type: string
        description: 'DBT Run Command'
        required: true

concurrency:
  group: ${{ github.workflow }}

jobs:
  ad_hoc:
    uses: ./.github/workflows/dbt.yml
    secrets: inherit
    with:
      warehouse: ${{ inputs.warehouse }}
      environment: ${{ inputs.environment }}
      command: ${{ inputs.dbt_command }}