name: dbt_run_dev_refresh
run-name: dbt_run_dev_refresh

on:
  workflow_dispatch:
  schedule:
    # Runs "at 9:00 UTC" (see https://crontab.guru)
    - cron: '0 9 * * *'

concurrency:
  group: ${{ github.workflow }}

jobs:
  dev_refresh:
    uses: ./.github/workflows/dbt.yml
    secrets: inherit
    with:
      environment: workflow_prod
      command: run-operation run_sp_create_prod_clone